stolostron/governance-policy-addon-controller

- config/rbac/role.yaml
- main.go
- pkg/addon/iam_policy/agent_addon.go
- pkg/addon/iam_policy/manifests/hub-permissions/role.yaml
- pkg/addon/iam_policy/manifests/hub-permissions/rolebinding.yaml
- pkg/addon/iam_policy/manifests/managedcluster-chart/Chart.yaml
- pkg/addon/iam_policy/manifests/managedcluster-chart/templates/_helpers.tpl
- pkg/addon/iam_policy/manifests/managedcluster-chart/templates/cluster_role.yaml
- pkg/addon/iam_policy/manifests/managedcluster-chart/templates/cluster_role_binding.yaml
- pkg/addon/iam_policy/manifests/managedcluster-chart/templates/deployment.yaml
- pkg/addon/iam_policy/manifests/managedcluster-chart/templates/leader_election_role.yaml
- pkg/addon/iam_policy/manifests/managedcluster-chart/templates/leader_election_role_binding.yaml
- pkg/addon/iam_policy/manifests/managedcluster-chart/templates/policy.open-cluster-management.io_iampolicy_crd.yaml
- pkg/addon/iam_policy/manifests/managedcluster-chart/templates/service_account.yaml
- pkg/addon/iam_policy/manifests/managedcluster-chart/values.yaml
- test/e2e/case3_iam_deployment_test.go
- test/resources/iam_policy_addon_cr.yaml
Signed-off-by: Chaitanya Kandagatla <ckandaga@redhat.com>
> iam policy controller addon

- config/rbac/role.yaml
- main.go
- pkg/addon/cert_policy/agent_addon.go
- pkg/addon/cert_policy/manifests/hub-permissions/role.yaml
- pkg/addon/cert_policy/manifests/hub-permissions/rolebinding.yaml
- pkg/addon/cert_policy/manifests/managedcluster-chart/Chart.yaml
- pkg/addon/cert_policy/manifests/managedcluster-chart/templates/_helpers.tpl
- pkg/addon/cert_policy/manifests/managedcluster-chart/templates/cluster_role.yaml
- pkg/addon/cert_policy/manifests/managedcluster-chart/templates/cluster_role_binding.yaml
- pkg/addon/cert_policy/manifests/managedcluster-chart/templates/deployment.yaml
- pkg/addon/cert_policy/manifests/managedcluster-chart/templates/leader_election_role.yaml
- pkg/addon/cert_policy/manifests/managedcluster-chart/templates/leader_election_role_binding.yaml
- pkg/addon/cert_policy/manifests/managedcluster-chart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
- pkg/addon/cert_policy/manifests/managedcluster-chart/templates/service_account.yaml
- pkg/addon/cert_policy/manifests/managedcluster-chart/values.yaml
- test/e2e/case4_cert_deployment_test.go
- test/resources/cert_policy_addon_cr.yaml
Signed-off-by: Chaitanya Kandagatla <ckandaga@redhat.com>
> cert policy controller addon

- .github/workflows/kind.yml
- sonar-project.properties
Relates to:
https://github.com/stolostron/backlog/issues/20014
The PR SonarCloud jobs will be done in Prow in a separate PR.
> Add the SonarCloud post-submit job

- Makefile
- build/Makefile.common.mk
- config/default/kustomization.yaml
- main.go
- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/policyframework/agent_addon.go
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
https://github.com/stolostron/backlog/issues/20017
Signed-off-by: Yu Cao <ycao@redhat.com>
> Adding linting

- pkg/addon/configpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_configurationpolicies_crd.yaml
Relates:
https://github.com/stolostron/backlog/issues/20006
https://github.com/stolostron/backlog/issues/19496
> Sync the ConfigurationPolicy CRD

- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/values.yaml
This will be replaced with a zap configuration
> Remove `--v` from IAM controller

- README.md
This documents the stand-alone annotations we currently have.
> Update README with information on the annotations

- README.md
Scans found a vuln in an installed package so new build will
update packages
Refs:
- https://github.com/stolostron/backlog/issues/22076
> Run a build to refresh our image

- pkg/addon/iampolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_iampolicy_crd.yaml
Refs:
- https://github.com/stolostron/backlog/issues/22322
> Update IAM CRD to allow remediationAction enforce

- README.md
No code changes, just need a build to pick up latest packages due to
a CVE
Refs:
- https://github.com/stolostron/backlog/issues/22446
> Run a new build to pick up new packages

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
Adds `LabelSelector` for namespaces. `ConfigurationPolicy` is being updated upstream:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/11
> Update `CertificatePolicy` CRD

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
Analogous to https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/10, but for the other policy controllers.
> Cert and IAM controller startup probes

- .github/workflows/kind.yml
- Makefile
- build/manage-clusters.sh
Reconcile with upstream:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/12
Closes https://github.com/stolostron/governance-policy-addon-controller/issues/63
> Add debug commands

- .github/workflows/kind.yml
- Makefile
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
- test/e2e/utils_test.go
Cherry-picks these PRs:
- https://github.com/stolostron/governance-policy-addon-controller/pull/60
- https://github.com/stolostron/governance-policy-addon-controller/pull/62
For https://github.com/stolostron/backlog/issues/23874
Might (should?) fail until https://github.com/stolostron/governance-policy-template-sync/pull/9 is merged.
> [release-2.5] cherry pick probes

- .github/workflows/kind.yml
- Makefile
- build/manage-clusters.sh
- main_test.go
Closes https://github.com/stolostron/governance-policy-addon-controller/issues/72
Includes the sonar cloud reporting.
> Implement test coverage

- .github/workflows/kind.yml
- .github/workflows/unit.yml
> Run workflows on release branches

- README.md
> No-op to re-trigger Prow

- Makefile
- README.md
- config/manager/manager.yaml
- pkg/addon/policyframework/agent_addon.go
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/leader_election_role.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/values.yaml
- test/e2e/case1_framework_deployment_test.go
Syncing the following PRs:
* open-cluster-management-io/governance-policy-addon-controller#25
Relates:
https://github.com/stolostron/backlog/issues/25999
Closes #96
> Sync from open-cluster-management-io/governance-policy-addon-controller: #25

- build/Dockerfile
- build/common/config/.golangci.yml
- go.mod
- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/policyframework/agent_addon.go
ref:
- https://github.com/stolostron/backlog/issues/26058
(cherry picked from commit bf8ec3ad5fe08b5896fe8b7a727692a7f4048087)
Closes #98
> Update to Go `v1.19`

- build/crd-sync.sh
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/cluster_role.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/cluster_role_binding.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/install-namespace.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/leader_election_role.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/leader_election_role_binding.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_iampolicy_crd.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/service_account.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/values.yaml
- test/e2e/case3_iam_deployment_test.go
for issue#
https://github.com/stolostron/backlog/issues/26178
Signed-off-by: Chaitanya Kandagatla <ckandaga@redhat.com>
> Hosted mode supoort for IAM Addon

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
The cert controller CRD was updated so running the CRD sync here.
Refs:
- https://github.com/stolostron/backlog/issues/26528
> Ran the crd sync

- .github/workflows/kind.yml
- Makefile
Sync upstream PR:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/35
Closes #118
> Sync from upstream - Set "minimum" tag in Makefile

- .github/workflows/kind.yml
- Makefile
> [release-2.5] Manual cherry-pick of #119

- pkg/addon/policyframework/agent_addon.go
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/monitoring_role.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/monitoring_role_binding.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/service.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/service_monitor.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/values.yaml
Heavily based on previous PR:
https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/13/
Refs:
- https://issues.redhat.com/browse/ACM-2179
(cherry picked from commit 570c4acca83595267fb68d8d785a15bc13344c5f)
Closes https://github.com/stolostron/governance-policy-addon-controller/issues/134
> Add Prometheus monitoring to the policy framework

- .ci-operator.yaml
- build/Dockerfile
- build/common/config/.golangci.yml
- go.mod
- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/policyframework/agent_addon.go
ref: https://github.com/stolostron/backlog/issues/27048
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
> [release-2.5] Upgrade to Go 1.19

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_iampolicy_crd.yaml
Syncs changes from:
- https://github.com/stolostron/cert-policy-controller/pull/201
- https://github.com/stolostron/iam-policy-controller/pull/165
ref: https://issues.redhat.com/browse/ACM-3049
> Add `policy-type=template` label to CRD

- Makefile
- build/manage-clusters.sh
- pkg/addon/policyframework/manifests/managedclusterchart/templates/cluster_role.yaml
> Manual sync for issue #188

- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
This is a non-automated cherry-pick of https://github.com/stolostron/governance-policy-addon-controller/pull/214
> [release-2.6] 🥸 Sync from open-cluster-management-io/governance-policy-addon-controller: #79

- README.md
Our prow CI detected a build failure that indicates we need to re-run the build.
Refs:
- https://github.com/stolostron/governance-policy-framework/actions/runs/6270712114
> Prow had failures with this image build so we need to retry

- Makefile
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/utils_test.go
Manual cherry-pick:
- https://github.com/stolostron/governance-policy-addon-controller/pull/296
> [release-2.7] Manual sync of ManagedClusterAddon timeout bump

- Makefile
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/utils_test.go
Manual cherry-pick:
- https://github.com/stolostron/governance-policy-addon-controller/pull/296
> [release-2.8] Manual sync of ManagedClusterAddon timeout bump

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
Just the additional updates for cert and iam
Refs:
- https://issues.redhat.com/browse/ACM-7778
> Allow configuring to emit error logs only

- .tekton/governance-policy-addon-controller-ocyz-pull-request.yaml
- .tekton/governance-policy-addon-controller-ocyz-push.yaml
- Dockerfile.rhtap
See the details in the associated task.
Refs:
- https://issues.redhat.com/browse/ACM-7178
> Add rhtap dockerfile with allowed image references

- README.md
> [release-2.7] Build refresh

- README.md
Ref: https://issues.redhat.com/browse/ACM-9031
> Add override troubleshooting in README

- config/rbac/role.yaml
- main.go
- pkg/addon/policyframework/agent_addon.go
- pkg/addon/policyframework/manifests/hubpermissions/compliance_history_api_role.yaml
- pkg/addon/policyframework/manifests/hubpermissions/compliance_history_api_rolebinding.yaml
- pkg/addon/policyframework/manifests/hubpermissions/compliance_history_api_sa.yaml
- pkg/addon/policyframework/manifests/hubpermissions/compliance_history_api_sa_secret.yaml
- pkg/addon/policyframework/manifests/hubpermissions/role.yaml
- test/e2e/case1_framework_deployment_test.go
- test/e2e/e2e_suite_test.go
> [Manual] Sync the upstream PRs: #133

- Dockerfile.rhtap
ref: https://issues.redhat.com/browse/ACM-9734
> Update RHTAP Dockerfile to Go v1.21

- .github/workflows/crd-sync.yml
- .github/workflows/kind.yml
- .github/workflows/unit.yml
- .github/workflows/upstream-refs.yml
- build/common/Makefile.common.mk
- build/crd-sync.sh
- config/rbac/role.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_configurationpolicies_crd.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_operatorpolicies_crd.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_iampolicy_crd.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/policy.open-cluster-management.io_policies_crd.yaml
Manual sync:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/132
And also adds CertificatePolicy and IamPolicy.
Closes #432
> [manual-sync] Upgrade `controller-gen`

- Makefile
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/utils_test.go
Manual sync of:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/140
Caveat: The label update commit will need to wait until OCM is synced to `stolostron`, since the update to `Singleton` mode as the defaut hasn't been synced yet. Skipped cherry-pick command for reference:
```
git cherry-pick -x 30ffb1766158394aabcb7fbaf8615bcd41f01d1e
```
Closes #454
> [manual-sync] Add debug logging

- Makefile
> [release-2.10] Set image registry for OCM images

- Makefile
> [release-2.9] Set image registry for OCM images

- Makefile
> [release-2.8] Set image registry for OCM images

- config/rbac/role.yaml
- go.mod
- go.sum
- main.go
Manual cherry-pick:
- #458 
ref: https://issues.redhat.com/browse/ACM-10280
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
(cherry picked from commit a094d75d96024789bb1fe5d56929187bb24156b5)
(cherry picked from commit 0000cea60c7047262cbb9ddab3f9c7b317adeadc)
> [release-2.8] Address CVE-2024-24786

- README.md
> [release-2.8] Build refresh

- Makefile
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
(cherry picked from commit 30ffb1766158394aabcb7fbaf8615bcd41f01d1e)
> Fix OCM label check

- build/crd-sync.sh
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_operatorpolicies_crd.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/policy.open-cluster-management.io_policies_crd.yaml
(cherry picked from commit cdccd557f9729c80f677175cd6b7bee2b244c0d3)
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/145
Closes #498
> [manual-sync] Sync CRDs

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
Sync descriptions from:
- https://github.com/stolostron/cert-policy-controller/pull/259
> Sync CertPolicy CRD

- Makefile
Should help the periodic tests pass for now
> Only warn when the ocm repo is not the latest

- pkg/addon/certpolicy/agent_addon.go
Relates:
https://issues.redhat.com/browse/ACM-11331
> Support install namespace on cert-policy-controller

- build/crd-sync.sh
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_configurationpolicies_crd.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_operatorpolicies_crd.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/policy.open-cluster-management.io_policies_crd.yaml
Manual cherry-pick:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/168
(cherry picked from commit cdb2f2b6b08bfd9b8d5070086fb238bbb9fc0c80)
Closes #621
> [manual-sync] Make CRD descriptions folded

- .tekton/governance-policy-addon-controller-acm-210-pull-request.yaml
- .tekton/governance-policy-addon-controller-acm-210-push.yaml
This update configures the SAST task to upload SARIF results to quay.io for
long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263
> fix(KONFLUX-3663): format PipelineRun files and upload SAST results

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/role.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/role_binding.yaml
issue: https://issues.redhat.com/browse/ACM-14380
> fix the cluster name is digital

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
Sync changes from:
- https://github.com/stolostron/cert-policy-controller/pull/495
> Sync CertificatePolicy CRD

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
> Fix: Add missing metrics container volume mount

- Makefile
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/auth_cluster_role.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/auth_cluster_role_binding.yaml
This is what I get for using a controller with `*/*/*` permissions as a guide. :joy:
Followup to:
- #793 
- #797
> Fix metrics RBAC for certpolicy

- .ci-operator.yaml
- .github/workflows/unit.yml
- build/Dockerfile
- build/Dockerfile.rhtap
- build/common/Makefile.common.mk
- go.mod
- go.sum
> [release-2.12] Address `oauth2` vuln

- .ci-operator.yaml
- .github/workflows/unit.yml
- build/Dockerfile
- build/Dockerfile.rhtap
- build/common/Makefile.common.mk
- go.mod
- go.sum
> [release-2.13] Address `oauth2` vuln

- .ci-operator.yaml
- .github/workflows/unit.yml
- build/Dockerfile
- build/Dockerfile.rhtap
- build/common/Makefile.common.mk
- go.mod
- go.sum
> [release-2.11] Address `oauth2` vuln

- Makefile
- test/resources/cert_policy_clustermanagementaddon.yaml
- test/resources/config_policy_clustermanagementaddon.yaml
- test/resources/framework_clustermanagementaddon.yaml
- test/resources/standalonetemplating_clustermanagementaddon.yaml
Includes changes from:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/205
> Add required `spec` to `ClusterManagementAddOn`

- .tekton/governance-policy-addon-controller-acm-214-push.yaml
Refs:
- https://issues.redhat.com/browse/ACM-20948
> Add multiarch build to konflux pipeline

- .ci-operator.yaml
- build/Dockerfile
- build/Dockerfile.rhtap
- build/common/Makefile.common.mk
- build/common/config/.golangci.yml
- go.mod
- main.go
- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/utils_test.go
ref: https://issues.redhat.com/browse/ACM-24264
> [release-2.13] Update to Go v1.24

- .ci-operator.yaml
- build/Dockerfile
- build/Dockerfile.rhtap
- build/common/Makefile.common.mk
- build/common/config/.golangci.yml
- go.mod
- main.go
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case3_compliance_db_secret_test.go
- test/e2e/case4_cert_deployment_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/utils_test.go
ref: https://issues.redhat.com/browse/ACM-24264
> [release-2.12] Update to Go v1.24

- .ci-operator.yaml
- build/Dockerfile
- build/Dockerfile.rhtap
- build/common/Makefile.common.mk
- build/common/config/.golangci.yml
- go.mod
- main.go
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case3_compliance_db_secret_test.go
- test/e2e/case4_cert_deployment_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/utils_test.go
ref: https://issues.redhat.com/browse/ACM-24264
> [release-2.11] Update to Go v1.24
