stolostron/governance-policy-addon-controller

- main.go
- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/policyframework/agent_addon.go
The simulation mode should help get things ready to be deployed via helm chart in a way that won't interfere with the current klusterlet-addon-controller setup.
> Refactor Agents and add simulation mode

- config/manager/manager.yaml
- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/certpolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/iampolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/policyframework/agent_addon.go
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/values.yaml
this PR depends the chart PR https://github.com/stolostron/grc-chart/pull/75
changes:
1. pass images of addons by env in addon-operator deployment.
2. `hubKubeConfigSecret` is a buildin value in addon-framework.
3.  `imagePullPolicy` is required as `IfNotPresent` by ACM.
4.  the default imagePullSecret is `open-cluster-management-image-pull-credentials`.
Signed-off-by: Zhiwei Yin <zyin@redhat.com>
> pass images by env

- config/rbac/role.yaml
- main.go
While testing in a live ACM cluster, it was found that it needed some
more permissions.
Refs:
- https://github.com/stolostron/backlog/issues/20013
> Add permissions for setting owner references

- config/manager/manager.yaml
- config/rbac/role.yaml
- main.go
- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/certpolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/iampolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/policyframework/agent_addon.go
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/values.yaml
The klusterlet-addon-controller was already updated to stop creating the grc addons, which means right now nothing is creating the deployments on managed clusters in snapshot builds. The helm chart has already been updated as well - but the fast-forward here is blocked by some other GRC test failures.
> Manually fast-forward to migrate control of grc addons

- config/rbac/role.yaml
- main.go
- pkg/addon/policyframework/manifests/hubpermissions/role.yaml
When running on a separate managed cluster (not "local-cluster") the spec-sync controller was restarting and logging errors about not being able to get this secret from the hub.
The issue with the lease name would probably only have been seen when testing with OCP 3.11 clusters.
> Fix framework permissions

- Makefile
- build/common/scripts/kubewait.sh
Make targets like `kind-deploy-registration-operator` were relying on
sleep intervals to wait for resources to appear. This was unreliable.
The new script waits for the namespace of the resource, then the
resource itself, and finally a condition on the resource, if specified.
> Add a script to help wait for kube resources

- .github/workflows/crd-sync.yml
- build/crd-sync.sh
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_configurationpolicies_crd.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_iampolicy_crd.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/policy.open-cluster-management.io_policies_crd.yaml
This should help keep the CRDs deployed by the addon-controller in sync
with the CRDs in the other repos. The v1beta1 CRDs are necessary for
older versions of kubernetes, but are not generated and stored in each
repo, so they must be generated specially.
The workflow defined here will not automatically update the CRDs, but
could be expanded in the future. For now it just runs nightly, but
doesn't alert anyone automatically.
Refs:
- https://github.com/stolostron/backlog/issues/19031
> Add and run crd-sync script

- README.md
To accommodate for Prow build failures
> no-op build

- .github/workflows/kind.yml
- .gitignore
- Makefile
- README.md
- build/common/Makefile.common.mk
- build/manage-clusters.sh
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/utils.go
- test/resources/cert_policy_addon_cr.yaml
- test/resources/config_policy_addon_cr.yaml
- test/resources/framework_addon_cr.yaml
- test/resources/iam_policy_addon_cr.yaml
Apparently Ginkgo doesn't know the value of anything in `BeforeSuite` until the `Describe` and `It` have already been evaluated, so wrapping an `It` statement in a loop didn't work. I had to nest the `for` loops to iterate over the clusters inside of the `It` functions, which meant I reflowed pretty much all of the tests. However I was trying to test one cluster at a time but then realized that I could have had a loop inside of each `It` statement, the benefit being that it would probably be slightly faster (and perhaps more realistic?) but less isolated.
Addresses:
- https://github.com/stolostron/backlog/issues/20016
> Add managed cluster tests

- Makefile
- pkg/addon/common.go
- test/e2e/case1_framework_deployment_test.go
- test/e2e/e2e_suite_test.go
- test/resources/manifestwork_add_patch.json
Setting the `policy-addon-pause=true` annotation will effectively pause the reconciliation of the ManifestWork, allowing on-the-fly edits.
Also removed some now-unused code
> Add pause annotation

- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/policyframework/agent_addon.go
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/values.yaml
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
- test/e2e/e2e_suite_test.go
- Uses the new `--log-level` and `--log-encoder` flags to set a default logging level for all controllers
- Sets package logging (configurable with `--v`) to be two levels less than the component logging level
- Default settings:
```
--log-encoder=console
--log-level=0
--v=-1
```
Addresses:
- https://github.com/stolostron/backlog/issues/19030
> Configure log level and encoding for addons

- pkg/addon/policyframework/manifests/managedclusterchart/templates/cluster_role.yaml
The framework controllers no longer manage the cluster namespace on
managed clusters, so this permission is unnecessary now.
Refs:
- https://github.com/stolostron/backlog/issues/20826
> Remove framework's permissions for namespaces

- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
Not sure how this was missing before, but we found a bug because of it
on an OCP 3.11 cluster.
> Add legacy leader election arg to template-sync

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/values.yaml
The policy controllers were reading the hub kubeconfig from the secret
more "manually" before, which meant that the configs were not being
updated after they expired and the secret was updated. This mounts the
config through a secret, which is automagically updated.
Refs:
- https://github.com/stolostron/backlog/issues/22651
> Add volume mounts for hub kubeconfig

- .github/workflows/kind.yml
- Makefile
- build/common/config/.golangci.yml
- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/policyframework/agent_addon.go
New linting changes are required for go 1.18.
This is a fix for https://github.com/stolostron/governance-policy-addon-controller/issues/48
> Use new linting for go 1.18

- .github/workflows/kind.yml
- Makefile
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/utils_test.go
Cherry-picking https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/10
Fixes part of https://github.com/stolostron/backlog/issues/24148
> Startup probes

- README.md
A few prow image builds failed yesterday.  Didn't look into why so hoping a retry fixes it.
Refs:
- https://coreos.slack.com/archives/C02UXRV7QP8/p1663222190238259
> Retry prow build due to failure in last image build

- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/cluster_role.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/cluster_role_binding.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/install-namespace.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/leader_election_role.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/leader_election_role_binding.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/service_account.yaml
- pkg/addon/certpolicy/manifests/managedclusterchart/values.yaml
- test/e2e/case4_cert_deployment_test.go
Hosted mode support is needed for the certificate policy controller. This PR adds that support to the grc addon controller.  With this change a user can deploy the certificate controller on a hosting cluster to manage a separate managed cluster.
Refs:
- https://github.com/stolostron/backlog/issues/26177
> Add hosted mode support to cert policy in addon controller

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
The addons have the deployment strategy of "Recreate", so leader election is not applicable when the replicas are set to 1. In this case, leader election is disabled to reduce resource utilization on the Kubernetes API server.
Relates:
stolostron/backlog#26711
https://issues.redhat.com/browse/ACM-1867
> Disable leader election when the replicas are set to 1

- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/certpolicy/manifests/managedclusterchart/templates/install-namespace.yaml
- pkg/addon/iampolicy/agent_addon.go
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/install-namespace.yaml
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
Support for customized variables
Support for common klusterlet agent install namespace
related to: https://issues.redhat.com/browse/ACM-2141
Signed-off-by: Chaitanya Kandagatla <ckandaga@redhat.com>
> cert and iam addon enhancements for hosted mode

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
This is a backport of:
https://github.com/stolostron/governance-policy-addon-controller/pull/111
https://github.com/stolostron/governance-policy-addon-controller/pull/114
The addons have the deployment strategy of "Recreate", so leader election is not applicable when the replicas are set to 1. In this case, leader election is disabled to reduce resource utilization on the Kubernetes API server.
Relates:
https://github.com/stolostron/backlog/issues/26711
https://issues.redhat.com/browse/ACM-1867
> [release-2.6] Disable leader election when the replicas are set to 1

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
This is a backport of https://github.com/stolostron/governance-policy-addon-controller/pull/141.
The addons have the deployment strategy of "Recreate", so leader election is not applicable when the replicas are set to 1. In this case, leader election is disabled to reduce resource utilization on the Kubernetes API server.
Relates:
https://github.com/stolostron/backlog/issues/26711
https://issues.redhat.com/browse/ACM-1867
> [release-2.5] Disable leader election when the replicas are set to 1

- pkg/addon/iampolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_iampolicy_crd.yaml
- Add  newlines from `yq` update
Peer with:
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/51
The curious thing here is that Cert doesn't get the same update because it passes its manifests through Kustomize for some additional customizations, which removes the newlines 🤔 :
https://github.com/stolostron/cert-policy-controller/blob/78c9b25eed6348264b81f16d952bf018783b45cb/Makefile#L152-L154
> Update IAM CRD

- pkg/addon/configpolicy/manifests/managedclusterchart/templates/cluster_role.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/cluster_role_binding_crd_reader.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/cluster_role_crd_reader.yaml
This accidentally used a Role instead of a ClusterRole. The ClusterRole will be the same for all hosted clusters but the ClusterRoleBinding is unique per hosted cluster since there's no way for ManifestWork to merge the subjects array.
Relates:
https://issues.redhat.com/browse/ACM-2923
(cherry picked from commit 1eb607e3f1bb81e99fedf5bd9a8dcede3d572df4)
> Fix the CRD read permissions on hosted config-policy-controllers

- Makefile
- build/manage-clusters.sh
- pkg/addon/policyframework/manifests/managedclusterchart/templates/policy.open-cluster-management.io_policies_crd.yaml
This a temporary change for a hotfix image that will be reverted.
Relates:
https://issues.redhat.com/browse/ACM-3504
> Backport the spec.copyPolicyMetadata field for 2.6

- pkg/addon/policyframework/manifests/managedclusterchart/templates/policy.open-cluster-management.io_policies_crd.yaml
This reverts commit 6b073256e8a94a595364ead0170e017ee79f7110. This was a temporary commit for a hotfix build.
> Revert "Backport the spec.copyPolicyMetadata field for 2.6"

- build/crd-sync.sh
Manual cherry-pick of:
- open-cluster-management-io/governance-policy-addon-controller#65
This allows proactive PRs by specifying something like:
```bash
ORG=gh-user BRANCH=my-changes ./build/crd-sync.sh
```
(cherry picked from commit 55067ca7512e7ce97e20e800bd969a495034936c)
Closes #177
> Manual cherry-pick of #65 (Use org/branch fallbacks for sync script)

- pkg/addon/policyframework/manifests/managedclusterchart/templates/cluster_role_binding_crd_listwatch.yaml
Prior to this, the governance-policy-framework ClusterRoleBinding would have the same name for every hosted cluster on the hosting/management cluster. The generated ManifestWork objects would overwrite each other since it did not append to the subjects array. Using a unique name per hosted cluster like the config-policy-controller does will resolve this.
Relates:
https://issues.redhat.com/browse/ACM-4486
(cherry picked from commit cce56fadef78a48b33524d1c99888de59c7ec7d7)
> [release-2.7] Use a unique ClusterRoleBinding name to account for hosted mode

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/leader_election_role.yaml
- pkg/addon/iampolicy/manifests/managedclusterchart/templates/leader_election_role.yaml
ConfigMap permissions were only necessary for legacy leader election, which was removed.
ref: https://issues.redhat.com/browse/ACM-5042
> Remove ConfigMap permissions (IAM/Cert)

- pkg/addon/policyframework/agent_addon.go
- pkg/addon/policyframework/manifests/managedclusterchart/templates/cleanup_pod.yaml
- pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml
- test/e2e/case1_framework_deployment_test.go
- test/e2e/case2_config_deployment_test.go
- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
- test/e2e/e2e_suite_test.go
The bug was by deleting the hcp cluster, we see that all the ACM policies on the ACM hub are also deleted.
Signed-off-by: Yi Rae Kim <yikim@redhat.com>
(cherry picked from commit c89a259ee16d48951964fe4e26242f0cc543188c)
> [release-2.8]Ensure policies remain when hosting cluster is a hub 

- pkg/addon/policyframework/manifests/managedclusterchart/templates/namespace.yaml
- test/e2e/case1_framework_deployment_test.go
When syncPoliciesOnMulticlusterHub is true, it's indicating that the hub is imported by a global hub. The namespace must be created on the hub to sync policies from the global hub. The namespace also needs to be cleaned up when uninstalled, so the clean up pod is now enabled in this scenario too.
Relates:
https://issues.redhat.com/browse/ACM-7655
(cherry picked from commit 21c01f09f46b48d119036da819a0af0a3278a52c)
> [Manual Sync release-2.7] Create the cluster namespace when a hub is imported by a global hub

- test/e2e/case3_iam_deployment_test.go
- test/e2e/case4_cert_deployment_test.go
This is a follow up to the following commit to account for the IAM and Cert deployments:
10a1e44358567857ff1ae65e2b97e277ed346e5e
> Use the correct kubeconfig for hosted mode tests

- build/crd-sync.sh
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_operatorpolicies_crd.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/values.yaml
- test/e2e/case2_config_deployment_test.go
- test/e2e/e2e_suite_test.go
The current CRD is not what it will be for the actual release, but it will work for some tests, and the crd-sync will bring in updates when they are ready.
As an initial limitation, this will only enable the operator policy on OpenShift 4.x managed clusters. We can possibly expand this in the future, since OLM can be installed on other clusters.
Refs:
- https://issues.redhat.com/browse/ACM-9640
(cherry picked from commit dddb40e75266cf334760fae0c399bb84ad97670c)
Closes https://github.com/stolostron/governance-policy-addon-controller/issues/385
> Add CRD and enable OperatorPolicy

- config/rbac/role.yaml
- main.go
This will remove the log errors of:
controller failed to sync "governance-policy-framework", err: clustermanagementaddons.addon.open-cluster-management.io "governance-policy-framework" is forbidden: User "system:serviceaccount:open-cluster-management:grc-policy-addon-sa" cannot patch resource "clustermanagementaddons/status" in API group "addon.open-cluster-management.io" at the cluster scope
> Add missing clustermanagementaddons/status patch permissions

- Makefile
Adds a guard if a new backplane is released but the value hasn't been updated yet. (Currently set to the latest MCE `backplane-2.6` branch.)
ref: https://issues.redhat.com/browse/ACM-10392
> Build from stolostron ocm

- Makefile
Sets the OCM clone to the equivalent MCE `backplane-2.5` branch.
ref: https://issues.redhat.com/browse/ACM-10392
> [release-2.10] Build from stolostron ocm

- Makefile
Sets the OCM clone to the MCE `backplane-2.4` branch. (Apparently `backplane-2.3` that it should be set to doesn't exist, so `backplane-2.4` ought to suffice if the tests pass.)
ref: https://issues.redhat.com/browse/ACM-10392
> [release-2.8] Build from stolostron ocm

- Makefile
Sets the OCM clone to the equivalent MCE `backplane-2.4` branch.
ref: https://issues.redhat.com/browse/ACM-10392
> [release-2.9] Build from stolostron ocm

- Makefile
`REGISTRY` is too generic and is being unintentionally overridden in the framework tests.
Followup to:
- #467
> Use `OCM_REGISTRY`

- Makefile
`REGISTRY` is too generic and is being unintentionally overridden in the framework tests.
Manual cherry-pick of:
- #471
> [release-2.8] Use `OCM_REGISTRY`

- Makefile
`REGISTRY` is too generic and is being unintentionally overridden in the framework tests.
Manual cherry-pick of:
- #471
> [release-2.9] Use `OCM_REGISTRY`

- Makefile
Manual cherry-pick of:
- #471 
`REGISTRY` is too generic and is being unintentionally overridden in the framework tests.
> [release-2.10] Use `OCM_REGISTRY`

- pkg/addon/certpolicy/manifests/managedclusterchart/templates/policy.open-cluster-management.io_certificatepolicy_crd.yaml
This takes care of the CertificatePolicy one which wasn't in the sync from upstream PR.
Relates:
https://issues.redhat.com/browse/ACM-11498
> Add the missing subresources section for the v1beta1 CRD (CertificatePolicy)

- pkg/addon/policyframework/agent_addon.go
Syncing the following PRs:
* open-cluster-management-io/governance-policy-addon-controller#173
The original PR didn't play well with some changing Konflux configurations.
Closes https://github.com/stolostron/governance-policy-addon-controller/issues/642
> Re-Sync from open-cluster-management-io/governance-policy-addon-controller: #173

- Makefile
- config/rbac/role.yaml
- main.go
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/configpolicy/manifests/managedclusterchart/templates/deployment.yaml
- pkg/addon/configpolicy/manifests/managedclusterchart/values.yaml
- pkg/addon/policyframework/agent_addon.go
- pkg/addon/standalonetemplating/agent_addon.go
- pkg/addon/standalonetemplating/manifests/hubpermissions/role.yaml
- pkg/addon/standalonetemplating/manifests/hubpermissions/rolebinding.yaml
- pkg/addon/standalonetemplating/manifests/managedclusterchart/Chart.yaml
- pkg/addon/standalonetemplating/manifests/managedclusterchart/templates/_helpers.tpl
- pkg/addon/standalonetemplating/manifests/managedclusterchart/templates/secret.yaml
- pkg/addon/standalonetemplating/manifests/managedclusterchart/values.yaml
- test/e2e/case3_standalonetemplating_test.go
- test/resources/standalonetemplating_addon_cr.yaml
- test/resources/standalonetemplating_clustermanagementaddon.yaml
This addon provides a mechanism for the configuration-policy-controller (including both ConfigurationPolicy and OperatorPolicy) to access resources on the hub cluster in order to resolve "hub templates." The addon itself is very small, it is just some base RBAC resources and a secret on the managed cluster to help the user identify how to configure additional permissions. Mainly, the config-policy-controller needs to be configured to mount the new addon's hub kubeconfig and utilize it.
Refs:
- https://issues.redhat.com/browse/ACM-16089
(cherry picked from commit 9d1a7372f38e89b7d42c766808960f8160b14555)
Closes: https://github.com/stolostron/governance-policy-addon-controller/issues/790
> Add standalone-hub-templating addon

- pkg/addon/certpolicy/manifests/managedclusterchart/values.yaml
- test/e2e/case4_cert_deployment_test.go
Related to:
- #814 
- https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/198
> Fix: add missing `resources` key (CertPolicy)

- config/rbac/role.yaml
- main.go
- pkg/addon/certpolicy/agent_addon.go
- pkg/addon/common.go
- pkg/addon/configpolicy/agent_addon.go
- pkg/addon/policyframework/agent_addon.go
- pkg/addon/standalonetemplating/agent_addon.go
Sync of https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/199
Plus the similar change for cert-policy-controller.
Ref: https://issues.redhat.com/browse/ACM-18029
Closes https://github.com/stolostron/governance-policy-addon-controller/issues/830
> [manual-sync] Use informers for faster lookups
